import dns from 'dns';
import { URL } from 'url';
import { validateUrl } from './ssrf';
import { renderPageForCheck } from './worker';

/**
 * Result of a liveness/parking check performed before an asset is registered.
 * ok=false means the registration should be blocked; reason explains why.
 */
export interface SiteCheckResult {
  ok: boolean;
  reason?: string;
  parked?: boolean;
}

// Aftermarket / parking nameservers. A domain delegated to these is listed for
// sale or parked. NOTE: GoDaddy's *default* nameservers (domaincontrol.com) are
// used by real hosted sites too, so they are intentionally NOT listed here.
const PARKING_NAMESERVERS = [
  'afternic.com', 'sedoparking.com', 'sedo.com', 'cashparking.com', 'bodis.com',
  'parkingcrew.net', 'dan.com', 'undeveloped.com', 'above.com', 'hugedomains.com',
  'uniregistrymarket.link', 'uniregistry.com', 'namefind.com', 'voodoo.com',
  'fabulous.com', 'parklogic.com', 'skenzo.com', 'domainsponsor.com', 'sav.com',
];

// Parking-provider domains that appear in the raw HTML (script/link srcs, config)
// of a lander even when the visible text is rendered by JavaScript.
const PARKING_PROVIDER_DOMAINS = [
  'afternic.com', 'sedo.com', 'sedoparking.com', 'img.sedoparking.com', 'bodis.com',
  'parkingcrew.net', 'dan.com', 'undeveloped.com', 'cashparking.com', 'hugedomains.com',
  'uniregistry', 'above.com', 'domainsponsor.com', 'fabulous.com', 'voodoo.com',
  'namefind.com', 'parklogic.com', 'skenzo.com', 'sav.com/lander', 'domainmarket.com',
];

// Visible-text signatures for parking / for-sale landers (checked against the
// JavaScript-rendered text, so these appear even on client-rendered landers).
const PARKING_SIGNATURES: RegExp[] = [
  /\bbuy this domain\b/i,
  /\b(?:this )?domain (?:name )?is for sale\b/i,
  /\bthe domain\b[^.\n]{0,60}\b(?:is|may be) for sale\b/i,
  /\bdomain (?:name )?for sale\b/i,
  /\bmay be for sale\b/i,
  /\bget this domain\b/i,
  /\binterested in (?:this|buying this) domain\b/i,
  /\bthe (?:current )?owner of this domain\b/i,
  /\bparked (?:free )?(?:courtesy|domain|page)\b/i,
  /\bthis (?:web ?page|domain) is parked\b/i,
  /\bdomain parking\b/i,
  /\bcheckout the full list of domains\b/i,
  /\bthis webpage was generated by the domain owner\b/i,
  /\bpowered by (?:afternic|dan\.com|sedo|bodis|parkingcrew)\b/i,
];

const PARKING_HOSTS = [
  'sedo.com', 'sedoparking.com', 'bodis.com', 'afternic.com', 'hugedomains.com',
  'parkingcrew.net', 'dan.com', 'uniregistry.com', 'undeveloped.com', 'sav.com',
];

function apexDomain(hostname: string): string {
  const parts = hostname.split('.');
  if (parts.length <= 2) return hostname;
  return parts.slice(-2).join('.');
}

async function nameserversLookParked(hostname: string): Promise<boolean> {
  const candidates = [hostname, apexDomain(hostname)];
  for (const cand of candidates) {
    try {
      const ns = await dns.promises.resolveNs(cand);
      if (
        ns.some((n) => {
          const low = n.toLowerCase();
          return PARKING_NAMESERVERS.some((p) => low === p || low.endsWith('.' + p) || low.includes(p));
        })
      ) {
        return true;
      }
    } catch {
      /* try next candidate */
    }
  }
  return false;
}

function rawHtmlReferencesParking(html: string): boolean {
  const low = html.toLowerCase();
  return PARKING_PROVIDER_DOMAINS.some((d) => low.includes(d));
}

function extractTitle(html: string): string {
  const m = html.match(/<title[^>]*>([\s\S]{0,300}?)<\/title>/i);
  return m ? m[1].trim() : '';
}

function looksParkedByContent(title: string, body: string): boolean {
  const hay = `${title}\n${body.slice(0, 40000)}`;
  return PARKING_SIGNATURES.some((re) => re.test(hay));
}

/**
 * Decide whether a URL points at a real, live site or a parked/non-existent
 * one. Genuinely-down-but-real sites (connection refused, timeout, 5xx) are NOT
 * blocked. Non-resolving domains, domains on parking nameservers, and pages that
 * load a parking provider are rejected.
 */
export async function checkSiteLive(urlStr: string): Promise<SiteCheckResult> {
  // 1. SSRF validation (scheme, host, not private/reserved).
  const ssrf = await validateUrl(urlStr);
  if (!ssrf.valid) {
    return { ok: false, reason: ssrf.error || 'URL failed validation' };
  }

  // 2. Must resolve, else the domain does not exist.
  let hostname = '';
  try {
    hostname = new URL(urlStr).hostname;
    await dns.promises.lookup(hostname, { all: true });
  } catch {
    return { ok: false, reason: `Domain "${hostname}" does not resolve (site does not exist)` };
  }

  // 3. Nameserver check — catches for-sale/parked domains even when the lander
  //    is fully JavaScript-rendered and the raw HTML is an empty shell.
  if (await nameserversLookParked(hostname)) {
    return { ok: false, parked: true, reason: 'Domain is delegated to a parking/for-sale nameserver, not a real website' };
  }

  // 4. Render the page ONCE with JavaScript executed (headless browser). This is
  //    the reliable signal: a client-rendered "buy this domain" lander only
  //    shows its for-sale content after its scripts run, which a raw fetch never
  //    sees. Done a single time at registration, so the cost is irrelevant.
  const rendered = await renderPageForCheck(urlStr);
  if (rendered) {
    try {
      const finalHost = new URL(rendered.finalUrl).hostname.toLowerCase();
      if (PARKING_HOSTS.some((h) => finalHost === h || finalHost.endsWith('.' + h))) {
        return { ok: false, parked: true, reason: `Domain redirects to a parking/for-sale page (${finalHost})` };
      }
    } catch {
      /* ignore */
    }
    if (rawHtmlReferencesParking(rendered.html)) {
      return { ok: false, parked: true, reason: 'Page loads a domain-parking/for-sale provider — not a real website' };
    }
    if (looksParkedByContent(rendered.title, rendered.text)) {
      return { ok: false, parked: true, reason: 'Site appears to be a parked / for-sale placeholder, not a real website' };
    }
    return { ok: true };
  }

  // 5. Render failed (site unreachable via the browser). Fall back to a raw
  //    fetch signature check; if that also fails, allow it — a real site can be
  //    temporarily down and should still be monitorable.
  try {
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 8000);
    const res = await fetch(urlStr, { signal: controller.signal, redirect: 'follow' });
    clearTimeout(timeout);
    const ctype = (res.headers.get('content-type') || '').toLowerCase();
    if (res.status >= 200 && res.status < 400 && ctype.includes('text/html')) {
      const body = (await res.text()).slice(0, 60000);
      if (rawHtmlReferencesParking(body) || looksParkedByContent(extractTitle(body), body)) {
        return { ok: false, parked: true, reason: 'Site appears to be a parked / for-sale placeholder, not a real website' };
      }
    }
    return { ok: true };
  } catch {
    return { ok: true };
  }
}
